### ISSUE TITLE
Parameters with Templated values not working 

### ISSUE THREAD

**Issue by jrevol** [toedter/hal-explorer#15] opened 2020-10-05 08:30 UTC
hi

i'm using version 0.13.0

i have an issue with the templated links with a backend responding "application/hal+json" media type.

my link is like that:
` "compute-all": {
      "href": "http://localhost:8086/rest/internal/hpa/product-snapshots/_compute_all?application={application}",
      "templated": true
    },`
and the browser does not parse parameters as it would do with HalFom response, it only put "http://localhost:8086/rest/internal/hpa/product-snapshots/_compute_all?application=" without being able to change it.

i understand that HAL+Json is on the way to be deprecated but i would like the HAL_explorer to be compatible with both kind of api i got

**Comment by toedter** [comment] 2020-10-05 17:10
Hi Julian, I don't quite understand what the issue is.
A templated link only offers the semantics of a template. In your case, I would expect the template to be a bit different:

```
"compute-all": { 
   "href": "http://localhost:8086/rest/internal/hpa/product-snapshots/_compute_all{?application}", 
   "templated": true
}

```
to indicate that the endpoint expects a parameter `application`

**Comment by jrevol** [comment] 2020-10-05 17:37
When i use Hal+json, i go access to all the verbs like with the old hal-browser But the parameters are not parsed.
the GET wizard give me access to a Parameters part where i can type the 'application', but with the other verbs i go a body but i can't put templated RequestParam

**Comment by toedter** [comment] 2020-10-05 20:05
Please take a look at
https://hypermedia-movies-demo.herokuapp.com/hal-explorer/index.html#theme=Cosmo&uri=/api/
and click on movies
=> template params are displayed in a HAL-FORMS document

or
https://chatty42.herokuapp.com/hal-explorer/index.html#theme=Cosmo&uri=/api/
and click on the green arrow for getting chatty:messages
=>  template params are displayed in a HAL document

Could you please try to return

```
"compute-all": { 
   "href": "http://localhost:8086/rest/internal/hpa/product-snapshots/_compute_all{?application}", 
   "templated": true
}
```

instead of
```
"compute-all": { 
   "href": "http://localhost:8086/rest/internal/hpa/product-snapshots/_compute_all?application={application}",
   "templated": true
}
```

Then it should work.

**Comment by jrevol** [comment] 2020-10-06 08:04
I tried, here is what i got
`
http://localhost:8086/rest/internal/hpa/product-snapshots/toto?from={from}&to={to}{&application,strategy}
`

with spring endpoint:
`
@RequestParam(value=APPLICATION, required = false) String applicationName,
                                                                                    @RequestParam(FROM) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate from,
                                                                                    @RequestParam(TO) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate to,
                                                                                    @RequestParam(value = STRATEGY, required = false) CleanupStrategy strategy
`

Spring generate ?application={application} is its mandatory and {?application} if it's not.
My problem here is that if I have to set mandatory params in a POST (or any non-get), I can, i can only fill body.

I understand this is not very REST Compliant but this is not absurd, i can't change some of this mandatory params and for now i can't use the explorer because of that.

whe i try to use the POST, is fills the POST by 
`
http://localhost:8086/rest/internal/hpa/product-snapshots/toto?from=
`
that means the template is detected, only the params form is not displayed, which prevents me to navigate.

**Comment by toedter** [comment] 2020-10-06 10:04
Thanks, I see your point now, I will think about a solution.
Since there might always be flaws in the template interpretation, maybe it would help to make the Expanded URL editable, just in case something is missing or not interpreted correctly.

**Comment by jrevol** [comment] 2020-10-06 12:06
In addition, to that spring is ok with POST request on endpoints like _computes with params, but when i use HAL_FORMS_JSON media type, hal browser suppose that all my links are GET links so i can't use them like i can (except for parametrized one as you know) with HAL_JSON media type.
Is there a way to do that ?

**Comment by toedter** [comment] 2020-10-07 06:56
Since HAL-FORMS supports affordances with _templates, HAL-Explorer is interpreting these strictly. This is one of the main reasons to use HAL-FORMS in the first place. But I will think about an option to disable this behavior.

**Comment by jrevol** [comment] 2020-10-07 13:07
I agree with you and i like that very much for new api but i can't change legacy endpoint like that and it's quite sad to not being able to use hal explorer for them event if spring is able to expose them as "hal-form" mediatype

**Comment by toedter** [comment] 2021-01-15 11:56
Implemented support for URI templates for POST, PUT, and PATCH in the current snapshot. Will be in the next release.

**Closed by toedter** 2021-01-15 11:56 UTC
